# Generated by Django 2.2.4 on 2019-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=500)),
                ('length', models.CharField(max_length=50)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('link', models.CharField(default='/', max_length=500)),
                ('video', models.CharField(default='/', max_length=500)),
                ('abstract', models.TextField(default='')),
                ('short_description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
