# Generated by Django 2.2.4 on 2019-09-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='link',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='length',
        ),
        migrations.AddField(
            model_name='talk',
            name='slide',
            field=models.CharField(default='/', max_length=500),
        ),
        migrations.AddField(
            model_name='talk',
            name='speaker',
            field=models.CharField(default='Pierre Ablin', max_length=256),
            preserve_default=False,
        ),
    ]
