# Generated by Django 2.2.5 on 2019-10-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_auto_20190902_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='seminar date')),
                ('place', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='talk',
            name='place',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='talk',
            name='seminar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programme.Seminar'),
        ),
    ]
