# Generated by Django 2.2.5 on 2019-10-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_auto_20191014_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='seminar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programme.Seminar'),
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('institution', models.CharField(max_length=256)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.Seminar')),
            ],
        ),
    ]
