# Generated by Django 2.2.5 on 2019-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_auto_20191014_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='date',
            field=models.DateTimeField(verbose_name='seminar date'),
        ),
    ]
