# Generated by Django 2.2.5 on 2019-10-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_auto_20191014_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='time',
            field=models.TimeField(default='16:00', verbose_name='seminar time'),
        ),
    ]
