# Generated by Django 2.2.5 on 2019-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_auto_20191018_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(default='4pm', verbose_name='seminar time'),
        ),
    ]
