# Generated by Django 2.2.5 on 2019-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_auto_20191018_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(default='16:00', verbose_name='seminar time'),
        ),
    ]
