# Generated by Django 2.2.5 on 2020-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_attendees_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
