# Generated by Django 2.2.5 on 2020-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0010_seminar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='private_link',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
