# Generated by Django 3.2 on 2022-01-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0011_seminar_private_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='capacity',
            field=models.IntegerField(default=None, null=True, verbose_name='Capacity'),
        ),
    ]
