# Generated by Django 4.1.3 on 2023-01-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0012_seminar_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='capacity',
            field=models.IntegerField(default=200, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='place',
            field=models.CharField(default='TBA', max_length=500),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='private_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(default='12:15', verbose_name='seminar time'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='abstract',
            field=models.TextField(default='TBA'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='short_description',
            field=models.CharField(default='TBA', max_length=500),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(default='TBA', max_length=500),
        ),
    ]
